# Generated by Django 5.1.3 on 2025-01-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdf_file',
        ),
    ]
