# Generated by Django 5.1.3 on 2025-01-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_emailmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recipient', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
    ]
