# Generated by Django 5.1.3 on 2024-12-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
