# Generated by Django 5.1.3 on 2024-12-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_transaction_customer_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='customer_country',
            new_name='country',
        ),
    ]
