# Generated by Django 5.1.3 on 2024-12-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_rename_customer_country_transaction_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='country',
        ),
    ]
